### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by weide86** [kawaapp/qing#1]
import (
	"github.com/labstack/echo"
	"github.com/kawaapp/wsq/spamcheck"
)

本项目中用到的github.com/kawaapp/wsq/spamcheck，找不到，项目没法运行，请问怎么处理？，谢谢

**Comment by ntop001** [comment]
@weide86 项目是从我们原来的商业产品中剥离出来的，还有一些代码没有去掉，现在已经OK了。
